name: msUtils
version: ${project.version}
description: A Minecraft plugin with custom features for WhoMine
authors: [MinersStudios, p0loskun]
website: minersstudios.github.io

main: github.minersStudios.msUtils.Main
api-version: 1.18
database: false
softdepend:
  - AuthMe
  - ProtocolLib
  - DiscordSRV

commands:
  me:
    usage: ' ꀑ §cИспользуй: /<command> [сообщение]'
    description: Проигрывает событие в чате в радиусе 25 блоков
  try:
    usage: ' ꀑ §cИспользуй: /<command> [сообщение]'
    description: Рандомно определяет исход события и проигрывает его в радиусе 25 блоков
  spit:
    usage: ' ꀑ §cИспользуй: /<command>'
    description: Покажи свою дерзость и плюнь кому то в ебло
  fart:
    usage: ' ꀑ §cИспользуй: /<command>'
    description: Пердани вкусно на публику
  sit:
    usage: ' ꀑ §cИспользуй: /<command>'
    aliases: [ sit, s ]
    description: Сядь на картаны и порви жопу
  mute:
    usage: ' ꀑ §cИспользуй: /<command> [ID/Nickname] [время] [причина]'
    permission: msUtils.mute
    description: Замутить игрока
  privatemessage:
    usage: ' ꀑ §cИспользуй: /<command> [ID/Nickname] [сообщение]'
    aliases: [ privatemessage, pm ]
    description: Отправь другому игроку приватное сообщение
  unmute:
    usage: ' ꀑ §cИспользуй: /<command> [ID/Nickname]'
    permission: msUtils.mute
    description: Размутить игрока
  ban:
    usage: ' ꀑ §cИспользуй: /<command> [ID/Nickname] [время] [причина]'
    permission: msUtils.ban
    description: Забанить игрока
  unban:
    usage: ' ꀑ §cИспользуй: /<command> [ID/Nickname]'
    permission: msUtils.ban
    description: Разбанить игрока
  kick:
    usage: ' ꀑ §cИспользуй: /<command> [ID/Nickname] [причина]'
    permission: msUtils.kick
    description: Кикнуть игрока
  getmaploc:
    usage: ' ꀑ §cИспользуй: /<command>'
    permission: msUtils.mapLocation
    description: Добывает координаты карты находящейся в руке
  resourcepack:
    usage: ' ꀑ §cИспользуй: /<command>'
    aliases: [ resourcepack, rp ]
    description: Открывает меню с ресурспаками
  info:
    usage: ' ꀑ §cИспользуй: /<command> [ID]'
    permission: msUtils.info
    description: Выводит в чат информацию про игрока
  whitelist:
    usage: ' ꀑ §cИспользуй: /<command> [add/remove/reload] [ID/Nickname]'
    permission: msUtils.whitelist
    description: Удаляет/добавляет игрока в вайтлист

permissions:
  msUtils.info:
    default: op
  msUtils.ban:
    default: op
  msUtils.mute:
    default: op
  msUtils.kick:
    default: op
  msUtils.mapLocation:
    default: op
  msUtils.whitelist:
    default: op