name: msUtils
version: ${project.version}
description: A Minecraft plugin with custom features for WhoMine
authors: [MinersStudios, p0loskun]
website: minersstudios.github.io

main: github.minersStudios.msUtils.Main
api-version: 1.18
database: false
softdepend:
  - AuthMe
  - ProtocolLib
  - DiscordSRV

commands:
  me:
    usage: ' ꀑ §cИспользуй: /<command> <сообщение>'
    description: Проигрывает событие в чате в радиусе 25 блоков
  try:
    usage: ' ꀑ §cИспользуй: /<command> <сообщение>'
    description: Рандомно определяет исход события и проигрывает его в радиусе 25 блоков
  spit:
    usage: ' ꀑ §cИспользуй: /<command>'
    description: Покажи свою дерзость и плюнь кому то в ебло
  fart:
    usage: ' ꀑ §cИспользуй: /<command>'
    description: Пердани вкусно на публику
  mute:
    usage: ' ꀑ §cИспользуй: /<command> [ID] [время] <причина>'
    permission: msUtils.mute
    description: Замутить игрока
  unmute:
    usage: ' ꀑ §cИспользуй: /<command> [ID]'
    permission: msUtils.mute
    description: Размутить игрока
  ban:
    usage: ' ꀑ §cИспользуй: /<command> [ID] [время] <причина>'
    permission: msUtils.ban
    description: Забанить игрока
  unban:
    usage: ' ꀑ §cИспользуй: /<command> [ID]'
    permission: msUtils.ban
    description: Разбанить игрока
  kick:
    usage: ' ꀑ §cИспользуй: /<command> [ID] <причина>'
    permission: msUtils.kick
    description: Кикнуть игрока
  getmaploc:
    usage: ' ꀑ §cИспользуй: /<command>'
    permission: msUtils.mapLocation
    description: Добывает координаты карты находящейся в руке
  resourcepack:
    usage: ' ꀑ §cИспользуй: /<command>'
    aliases: [ resourcepack, rp ]
    description: Открывает меню с ресурспаками
  info:
    usage: ' ꀑ §cИспользуй: /<command> [ID]'
    permission: msUtils.info
    description: Выводит в чат информацию про игрока

permissions:
  msUtils.info:
    default: op
  msUtils.ban:
    default: op
  msUtils.mute:
    default: op
  msUtils.kick:
    default: op
  msUtils.mapLocation:
    default: op